# Generated by Django 4.2.7 on 2025-08-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_add_profile_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='highscore',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
