# Generated by Django 4.2.7 on 2025-08-07 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_add_google_id_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_id_temp',
        ),
    ]
